build:../gap.h ../comparators.h ../IO.h ../shellSort.h test.cpp
	g++ -O3 test.cpp ../shellSort.h ../comparators.h ../IO.h ../gap.h -o shellSort
run:build
	./shellSort
clean:
	rm -f shellSort sortedData
